### ISSUE TITLE
Can't package for Linux using UE 4.24

### ISSUE THREAD

**Issue by JanisCircenis** [feixuwu/UEWebsocket#74]
> UATHelper: Packaging (Linux):     ld.lld: error: undefined symbol: SSL_library_init
UATHelper: Packaging (Linux):     >>> referenced by ssl.c
UATHelper: Packaging (Linux):     >>>               ssl.c.o:(lws_context_init_ssl_library) in archive /Plugins/WebSocket/Source/WebSocket/ThirdParty/lib/Linux/libwebsockets.a
UATHelper: Packaging (Linux):   

I get a bunch of errors like this one when trying to package project for Linux
Full list of linker errors:

> PackagingResults: Error: undefined symbol: SSL_library_init
PackagingResults: Error: undefined symbol: OPENSSL_add_all_algorithms_noconf
PackagingResults: Error: undefined symbol: SSL_load_error_strings
PackagingResults: Error: undefined symbol: SSL_get_ex_new_index
PackagingResults: Error: undefined symbol: SSL_CTX_get_ex_new_index
PackagingResults: Error: undefined symbol: SSL_COMP_free_compression_methods
PackagingResults: Error: undefined symbol: ERR_free_strings
PackagingResults: Error: undefined symbol: EVP_cleanup
PackagingResults: Error: undefined symbol: SSL_COMP_free_compression_methods
PackagingResults: Error: undefined symbol: ERR_free_strings
PackagingResults: Error: undefined symbol: EVP_cleanup
PackagingResults: Error: undefined symbol: CRYPTO_cleanup_all_ex_data
PackagingResults: Error: undefined symbol: CRYPTO_cleanup_all_ex_data
PackagingResults: Error: undefined symbol: SSLv23_server_method

**Comment by feixuwu** [comment]
I will check linux package problem this weekend

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by rtar** [comment]
The reason is that included `libwebsocket.a` depends on older OpenSSL version (1.0.2h?) and it is not compatible with latest one provided by OpenSSL module (1.1.1c?) in UE 4.24.

The fix could be uploading an updated `libwebsocket.a` or changing build file to depend on older OpenSSL version (which is still included into UE 4.24).

**Comment by feixuwu** [comment]
Yes, unreal engine use different version openssl in deferent platform,  anyway, I submit a fix, it should fix the problem.
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Ruslans Tarasovs<mailto:notifications@github.com>
发送时间: 2020年2月20日 6:20
收件人: feixuwu/UEWebsocket<mailto:UEWebsocket@noreply.github.com>
抄送: xufeiwu<mailto:feixuwu@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [feixuwu/UEWebsocket] Can't package for Linux using UE 4.24 (#74)


The reason is that included libwebsocket.a depends on older OpenSSL version (1.0.2h?) and it is not compatible with latest one provided by OpenSSL module (1.1.1c?) in UE 4.24.

The fix could be uploading an updated libwebsocket.a or changing build file to depend on older OpenSSL version (which is still included into UE 4.24).

―

**Comment by JanisCircenis** [comment]
Linux build still fails. You should recompile libwebsockets424.a with -fPIC param. I did that and it worked.

**Comment by feixuwu** [comment]
I packet it for linux success, so what is the error?
this lib is not dynamic library, so shoud not need -fPIC.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
发件人: JanisCircenis <notifications@github.com>
发送时间: 2020年2月26日星期三 22:38
收件人: feixuwu/UEWebsocket
抄送: xufeiwu; Comment
主题: Re: [feixuwu/UEWebsocket] Can't package for Linux using UE 4.24 (#74)


Linux build still fails. You should recompile libwebsockets424.a with -fPIC param. I did that and it worked.

―

**Comment by JanisCircenis** [comment]
I got this error whrn packaging:
`<EnginePath>/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-ld: <UEProject>/Plugins/WebSocket/Source/WebSocket/ThirdParty/lib/Linux/libwebsockets424.a(libwebsockets.c.o): relocation R_X86_64_PC32 against symbol `_lws_log' can not be used when making a shared object; recompile with -fPIC`

**Comment by feixuwu** [comment]
u build on windows use cross build or build on linux?

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by JanisCircenis** [comment]
That happened on Linux. I compiled libwebsockets424.a with -fPIC parameter and the error disappeared.

**Comment by feixuwu** [comment]
Em, it’s strange, I can use cross package on my PC,
Anyway, I recompile libwebsockers424 with -fPIC enable, and submitted the library,
Please help confirm it works on Linux packakge.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: JanisCircenis<mailto:notifications@github.com>
发送时间: 2020年2月27日 15:40
收件人: feixuwu/UEWebsocket<mailto:UEWebsocket@noreply.github.com>
抄送: xufeiwu<mailto:feixuwu@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [feixuwu/UEWebsocket] Can't package for Linux using UE 4.24 (#74)


That happened on Linux. I compiled libwebsockets424.a with -fPIC parameter and the error disappeared.

―

**Comment by feixuwu** [comment]
it is because your g++ enabled pie, if use cross build it will success,
however,I submitted a fix, with -fPIC to build the libwebsockets
